### ISSUE TITLE
Carthage build crashed on Xcode 11

### ISSUE THREAD

**Issue by denis-ionov** [abbeycode/UnzipKit#102]
Xcode version 11.2.1 (11B500)
UnzipKit version 1.9

Build error:
```
*** Building scheme "UnzipKit" in UnzipKit.xcworkspace
Build Failed
	Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -workspace /Users/user/app/Carthage/Checkouts/UnzipKit/UnzipKit.xcworkspace -scheme UnzipKit -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/UnzipKit/1.9 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/47/8s7xd_sd7c3b1kf_y482fkkm0000gn/T/UnzipKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/user/app/Carthage/Checkouts/UnzipKit)
```

Carthage log:
```
...
/Users/user/app/Carthage/Checkouts/UnzipKit/Source/UZKArchive.m:2065:40: error: implicit conversion loses integer precision: 'const UZKCompressionMethod' (aka 'const enum UZKCompressionMethod') to 'int' [-Werror,-Wshorten-64-to-32]
...
```

It seems that the problem in type casting.

**Comment by abbeycode** [comment]
Thanks for pointing this out! I'll take a look at getting the next version (v2.0, in beta now) to compile cleanly on Xcode 11.

**Comment by abbeycode** [comment]
I just verified that it looks like Carthage should work fine on v2.0, if you want to start using that branch.
